server:
  port: 8080
#  servlet:
#    contextPath: /api

spring:
  application:
    name: gateway


eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    crm:
       path: /crm/**
       serviceId: crm
       
    security:
       path: /security/**
       serviceId: security
       
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    socket-timeout-millis: 30000