server:
  port: 8080
  
spring:
  application:
    name: API Gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    crm:
       path: /crm/**
       serviceId: crm
  host:
    socket-timeout-millis: 30000